name: CI
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
 continous-integration:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in ~/.npm on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install node
        uses: actions/setup-node@v2
        with:
            node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Install Cypress
        run: npm i --save-dev cypress
      - name: Install Cypress partII
        run: npm run test-in
      - name: unit-test with cypress
        run: npm test
 continous-deployment:
    runs-on: ubuntu-latest
    needs: [continous-integration]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: if CI clear
        run: echo "congrats"
